entrypoint: "gunicorn -b :$PORT app:app --timeout 500"
runtime: python
env: flex
service: nyc-price-prediction
runtime_config:
python_version: 3.10
instance_class: F1
manual_scaling:
  instances: 1
liveness_check:
  path: "/liveness_check"